name: CI
on:
  push:
  pull_request:
jobs:
  check:
    name: Build
    runs-on: ubuntu-latest
    if: "github.event_name == 'push' || github.event.pull_request.head.repo.full_name != github.repository"
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v3
      - name: Run cargo clippy
        run: cargo clippy -- -D warnings
      - name: Run cargo fmt
        run: cargo fmt --check
      - name: Run tests
        run: cargo test
