name: Docker
on:
  release:
    types: [released]
jobs:
  docker:
    name: Build and Publish Docker Image
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}/exporter:${{ github.ref_name }}
            ghcr.io/${{ github.actor }}/${{ github.event.repository.name }}/exporter:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
