name: Publish release
on:
  workflow_dispatch:
jobs:
  create_release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Retrieve Crate Version
        id: crate-version
        run: echo version=$(cargo metadata --format-version 1 --no-deps | jq -rc '.packages[] | select( .name == "traewelling-exporter") | .version') >> $GITHUB_OUTPUT
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          tag_name: ${{ steps.crate-version.outputs.version }}
          token: ${{ secrets.GH_SECRET }}
